import type { Metadata } from "next";
import { Geist, Geist_Mono, Iceland, Gudea ,Inter } from "next/font/google";
import "./globals.css";
import Footers from "@/Component/Footers";
import Headers from "@/Component/Headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({
    subsets: ['latin'],
  weight: '400',
})

const gudea = Gudea({
    subsets: ['latin'],
  weight: '400',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <body   className={inter.className}
      >
        <Headers/>
        <main className="pt-40">{children}</main>

       <Footers/>
      </body>
    </html>
  );
}
